<?php

namespace Drupal\custom_module\Form;

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\Node;

class batchForm extends \Drupal\Core\Form\ConfigFormBase
{

  /**
   * @inheritDoc
   */
  protected function getEditableConfigNames()
  {
    // TODO: Implement getEditableConfigNames() method.
  }

  /**
   * @inheritDoc
   */
  public function getFormId()
  {
    return 'batch_form';
  }

  public function buildForm(array $form, FormStateInterface $form_state)
  {

    $options = [
      'article' => "Article"
    ];
    $form['node_type'] = [
      '#type' => "select",
      '#options' => $options,
      '#default_value' => 'article'
    ];

    return parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  public function submitForm(array &$form, FormStateInterface $form_state)
  {
    $node_type = $form_state->getValues()['node_type'];

    $nids = \Drupal::entityQuery('node')
      ->condition('type', $node_type)
      ->execute();

    $batch = [
      'title' => 'Nodes Updating...',
      'operations' => [],
      'init_message' => "Connecting..",
      'progress_message' => t('Processed @current out of @total.'),
      'finished'=>'\Drupal\custom_module\Form\batchForm::finished'
    ];
    $_batch = array_chunk($nids, 2);
    foreach ($_batch as $_batchPart){
      $batch['operations'][] = [
        '\Drupal\custom_module\Form\batchForm::updatingTitle',
        [$_batchPart]
      ];
    }
    batch_set($batch);
//    parent::submitForm($form, $form_state);
  }

  public static function updatingTitle($_batch_nodes){
    foreach ($_batch_nodes as $node_id){
      $node = Node::load($node_id);
      $node->setTitle($node->getTitle().' Textxxx');
      $node->save();
    }
  }

  public function finished(){
    return "Successfully done.";
  }
}
